version: "3"

services:

  database:
    build:
      context: ./packages/database
      dockerfile: Dockerfile
    container_name: whatsapp-clone-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    container_name: whatsapp-clone-server
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: whatsapp
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      JWT_SECRET: 321412zcv987asf87b78as8d
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - database

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    container_name: whatsapp-clone-client
    ports:
      - "8080:8080"
    depends_on:
      - server
