# fly.toml app configuration file generated for whatsapp-clone-server on 2023-06-13T23:33:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whatsapp-clone-server"
primary_region = "bog"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
