# Test Actions
name: CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install Babel
      run: |
        cd ${{ github.workspace }}
        npm install
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}/packages/server
        npm install
    - name: Run tests
      run: |
        cd ${{ github.workspace }}/packages/server
        npm test
