name: CI

on:
  push:
    branches: [ Test-Actions ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install dependencies
      run: |
        cd server
        npm install
    - name: Run tests
      run: |
        cd server
        npm test
